common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password:

development:
  <<: *common
  database: ht_dev


production:
  <<: *common
  database: ht_dev
  